Repository 2dubu/LetsBookCrossing, pull requests merged in 2022-09, with the labels that each got.

#15 #5 refactor: 필요 없는 로직 제거 및 레거시 코드 제거
  BookBori/BookBori/ViewController/Check/CheckViewController.swift
  BookBori/BookBori/ViewController/Register/CompleteRegisterViewController.swift
Labels: refactor, cleanup

#14 Roun/#13
  BookBori/BookBori/Model/DummyData.swift
  BookBori/BookBori/View/Storyboard/Base.lproj/Main.storyboard
  BookBori/BookBori/ViewController/HowToUseViewController.swift
Labels: refactor

#16 #6 fix: custom refresh control 버그 수정
  BookBori/BookBori/ViewController/SelectBookViewController.swift
Labels: improvement

#17 #7 feat: 화면 전환 로딩 시 애니메이션 처리
  BookBori/BookBori/View/Storyboard/Base.lproj/Main.storyboard
  BookBori/BookBori/ViewController/MainViewController.swift
Labels: improvement, feature
